### ISSUE TITLE
run-host exits with silent error if illegal param --dns-ip-range

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti-tunnel-sdk-c#617] opened 2023-03-19 04:02 UTC
~~I installed the DEB package in Ubuntu Jammy 22.04 running in LXC. I can run ZET run-host as root, but it always exits immediately with an error if it's invoked by systemd. I set `ZITI_LOG=4 UV_MBED_DEBUG=4` and `--verbose=6` but it exits before those take effect, apparently, because there's no output.~~

EDIT: this was a red-herring. See follow-up comment.

```
Mar 19 03:59:48 jammy1 systemd[1]: Started Ziti Edge Tunnel.
Mar 19 03:59:48 jammy1 systemd[1]: ziti-edge-tunnel.service: Main process exited, code=exited, status=1/FAILURE
Mar 19 03:59:48 jammy1 systemd[1]: ziti-edge-tunnel.service: Failed with result 'exit-code'.
```

**Comment by qrkourier** [comment] 2023-03-19 13:51
Good news, `run-host` works in LXC just fine. The problem was an illegal param for `run-host --dns-ip-range`. The process exits with a silent error code, no error message. I've changed this issue to reflect the bug of no error message.

```bash
$ /opt/openziti/bin/ziti-edge-tunnel run-host --identity /opt/openziti/etc/identities/lke-edge-client.json --verbose 4 --dns-ip-range=100.80.0.0/12
About to run tunnel service that hosts services... ziti-edge-tunnel

$ echo $?
130
```

**Comment by dovholuknf** [comment] 2023-03-19 16:26
possible duplicate of https://github.com/openziti/ziti-tunnel-sdk-c/issues/184 ?

**Comment by qrkourier** [comment] 2023-03-19 16:48
Yes, same problem but for a different sub-command. I'm not sure whether fixing one would fix both.

**Comment by qrkourier** [comment] 2023-10-14 16:44
This problem still exists in 0.22.11 from the test release repo.

```bash
❯ ziti-edge-tunnel run-host --identity /opt/openziti/etc/identities/bastion1.json --verbose 4 --dns-ip-range=100.80.0.0/12 || echo $?
1

❯ ziti-edge-tunnel version                                                                                                           
v0.22.11-local

❯ apt show ziti-edge-tunnel                                                                                                          
Package: ziti-edge-tunnel
Version: 0.22.11
Priority: optional
Section: devel
Maintainer: support@netfoundry.io
Installed-Size: 4,556 kB
Depends: debconf, iproute2, sed, systemd, libatomic1, libssl3 | libssl1.1 | libssl1.0.0, login, passwd, policykit-1, zlib1g
Download-Size: 1,976 kB
APT-Manual-Installed: yes
APT-Sources: https://packages.openziti.org/zitipax-openziti-deb-test jammy/main amd64 Packages
Description: ziti-tunnel-sdk-c built using CMake

N: There are 15 additional records. Please use the '-a' switch to see them.
```

**Closed** 2024-06-05 21:02 UTC
