### ISSUE TITLE
DnsClientNrptRule is being created on hosting service identity OS

### ISSUE THREAD

**Issue by emoscardini** [openziti/ziti-tunnel-sdk-c#971] opened 2024-09-17 18:27 UTC
Setup:

WDE installed on a DC hosting a service.
WDE installed on a remote machine that needs to join the domain & is intercepting a wildcard service.  Expects SRV records to resolve from the remote side. Using a command like `Resolve-DnsName _ldap._tcp.dc._msdcs.ziti.contoso.com -Type SRV` to test.

Issue: 
While hosting using WDE, a DnsClientNrptRule is inserted for the service.

Expected behavior:

A DnsClientNrptRule should only be created if the identity is intercepting a specified service not hosting it. 

See [WDE Breaks Windows DNS on DC](https://openziti.discourse.group/t/wde-breaks-windows-dns-on-dc/3140/1) for more details

**Comment by nenkoru** [comment] 2024-09-17 19:48
Wow. That's awesome!
Thank you @dovholuknf and @emoscardini for a fast root cause analysis and a fix for this!!!

**Comment by dovholuknf** [comment] 2024-09-18 01:17
As mentioned previously, I am using the "main" branch of the ziti-edge-tunnel for the upcoming ZDEW release after a soak period. The plan will be to update the release stream known as `ctrlha-alpha` (https://get.openziti.io/zdew/ctrlha-alpha.json) for a few days. Me and @emoscardini are using this stream as our daily driver. Hopefully, any huge issues we'll hit quickly. After that it'll be promoted to the beta stream. After that to the latest stream and after soaking for a while in 'latest', I'll promote it to stable. I'm unsure of the exact timeframe for the promotions but if you are interested you can grab the 2.5.0.6 release of the ZDEW from the alpha release I just created here https://github.com/openziti/desktop-edge-win/releases/tag/2.5.0.6-alpha

If you are interested in following the stream and being really brave with 'dripping wet' code you can configure automatic upgrades with the url: https://get.openziti.io/zdew/ctrlha-alpha.json. This version should have the current proposed fix for this issue in it. @emoscardini hasn't tested it yet for this issue, hopefully he can tomorrow our time.
![image](https://github.com/user-attachments/assets/a7e3fe32-a6a8-4352-b389-9113839d3e48)

**Comment by nenkoru** [comment] 2024-09-18 17:38
> As mentioned previously, I am using the "main" branch of the ziti-edge-tunnel for the upcoming ZDEW release after a soak period. The plan will be to update the release stream known as `ctrlha-alpha` (https://get.openziti.io/zdew/ctrlha-alpha.json) for a few days. Me and @emoscardini are using this stream as our daily driver. Hopefully, any huge issues we'll hit quickly. After that it'll be promoted to the beta stream. After that to the latest stream and after soaking for a while in 'latest', I'll promote it to stable. I'm unsure of the exact timeframe for the promotions but if you are interested you can grab the 2.5.0.6 release of the ZDEW from the alpha release I just created here https://github.com/openziti/desktop-edge-win/releases/tag/2.5.0.6-alpha
> 
> If you are interested in following the stream and being really brave with 'dripping wet' code you can configure automatic upgrades with the url: https://get.openziti.io/zdew/ctrlha-alpha.json. This version should have the current proposed fix for this issue in it. @emoscardini hasn't tested it yet for this issue, hopefully he can tomorrow our time. ![image](https://private-user-images.githubusercontent.com/46322585/368387731-a7e3fe32-a6a8-4352-b389-9113839d3e48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2ODEzMzksIm5iZiI6MTcyNjY4MTAzOSwicGF0aCI6Ii80NjMyMjU4NS8zNjgzODc3MzEtYTdlM2ZlMzItYTZhOC00MzUyLWIzODktOTExMzgzOWQzZTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDE3MzcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3OTlhOTAwZGI0NDA1YWI2MGU1MzVmOWM1MWM3ZmY5NTg4YTA5MWRhYjM4Yjk2NmU0OTcxMDljZDMwZDQ0OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._LGHXn9wqyfQdHeUQO_a5cGG7PA41qASDDeOxQzFoE0)

I would definitely switch to the alpha branch and will do tests to try thefround-robin HA DC setup and see how it goes!
Thank you once more!

**Comment by nenkoru** [comment] 2024-09-18 17:40
> Actually - hold on. I forgot to follow-up here. I 2.5.0.6 won't have the latest tunneler for this issue. It'll be in 2.5.0.7 (i used the wrong ziti-edge-tunnel)... I'll follow up with 2.5.0.7 is published

Got it!

**Comment by dovholuknf** [comment] 2024-09-18 21:53
@nenkoru - 2.5.0.7 was just published. I confirmed versions before have an NRPT entry with Namespace for a "bind only" service, and 2.5.0.7 no longer should.

If you could test and verify - that'll be much appreciated

![image](https://github.com/user-attachments/assets/ec87c8fb-b872-4009-8827-fd012cded5a0)

**Comment by emoscardini** [comment] 2024-09-19 13:58
Thank you @dovholuknf  I have confirmed in my setup that everything is working as expected now.  The hosting side is no longer creating the NrptRule & queries are flowing without making any adjustments.

**Comment by dovholuknf** [comment] 2024-09-19 14:04
@emoscardini reported logging it no longer logging...  i noticed that too and @scareything has a fix... 2.5.0.8 will be coming shortly... :D

**Comment by dovholuknf** [comment] 2024-09-20 02:05
Well we got logs back in 2.5.0.8, but with the latest updates to the ZDEW monitor service, the logs are now getting filled with extraneous log messages from the monitor... 2.5.0.9 ZDEW will come tomorrow... I'm going to close this issue though because the original issue is actually fixed...

**Closed by dovholuknf** 2024-09-20 02:05 UTC

**Comment by nenkoru** [comment] 2024-11-03 17:16
I confirm the issue is resolved. Tested with 2.5.0.11. 
Any luck getting this backported to 2.4.*?
